# Generated by Django 4.2.5 on 2023-09-21 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_title_section_name_book_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='book',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
